//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerLine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ทดสอบจุดที่ 1")]
        public string Location {
            get {
                return ((string)(this["Location"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ทดสอบการแจ้งเตือนระบบตรวจสอบกระแสไฟฟ้า")]
        public string NotifyMessage {
            get {
                return ((string)(this["NotifyMessage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastNotifyDateTime {
            get {
                return ((global::System.DateTime)(this["LastNotifyDateTime"]));
            }
            set {
                this["LastNotifyDateTime"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLineNotify {
            get {
                return ((bool)(this["EnableLineNotify"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableSmsNotify {
            get {
                return ((bool)(this["EnableSmsNotify"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NotifyPeriodInMinutes {
            get {
                return ((int)(this["NotifyPeriodInMinutes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77684d70357e99a163877e6fc45c3561")]
        public string LineChannelSecret {
            get {
                return ((string)(this["LineChannelSecret"]));
            }
            set {
                this["LineChannelSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PzmEFnemYZl+GDkyVQDn/V9v/FJ+1s4EoGLL5PWTSVPdHNMJ+c76/ZEmHfwXa4vW0d4aJJrdCW/50aMVM" +
            "3RkVRwqJXIjDSck25hqUeRh7rrzkaGBSJU22mf3ZylQwryvV36GSrCId/RPST0BWVZL0gdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string LineChannelAccessToken {
            get {
                return ((string)(this["LineChannelAccessToken"]));
            }
            set {
                this["LineChannelAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int IntervalCheckTimeInMillisecond {
            get {
                return ((int)(this["IntervalCheckTimeInMillisecond"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.line.me/v2")]
        public string LineEndponintApi {
            get {
                return ((string)(this["LineEndponintApi"]));
            }
            set {
                this["LineEndponintApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableErrorNotify {
            get {
                return ((bool)(this["EnableErrorNotify"]));
            }
            set {
                this["EnableErrorNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ทดสอบการแจ้งเตือนระบบตรวจสอบกระแสไฟฟ้า")]
        public string ErrorMessage {
            get {
                return ((string)(this["ErrorMessage"]));
            }
            set {
                this["ErrorMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastErrorDateTime {
            get {
                return ((global::System.DateTime)(this["LastErrorDateTime"]));
            }
            set {
                this["LastErrorDateTime"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1440")]
        public int NotifyErrorPeriodInMinutes {
            get {
                return ((int)(this["NotifyErrorPeriodInMinutes"]));
            }
        }
    }
}
